### PR TITLE
Add: flymake backend for haml-lint & lexical binding

### PR DESCRIPTION
**Pull request by gcentauri**
Hello! 👋🏽 

I've sketched up a draft of a Flymake backend for `haml-lint` https://github.com/sds/haml-lint based on a similar implementation for Ruby's Flymake backends. So far its working for me:

image

I'm currently using this in daily dev work, so hoping to iron out any issues, but I thought I'd open this PR for feedback and discussion.

@purcell - I know you have a repo for `flymake-haml` but it seems to be written for an older version of Flymake? I'm not 100% sure on that, so let me know if this might fit in better with that repo.

Thanks!

### CODE REVIEW

**Comment by gcentauri** [comment]
Oh, I also added `lexical-binding: t` to this file, it was necessary to get some of the variables to work correctly with the process sentinel callback. There's a few other warnings around variables, but I didn't touch any existing ones, hopefully it won't break anything.

**Comment by purcell** [comment]
Thanks. I just added a CI config so I'll close and then re-open this PR to trigger a fresh rebase and CI run...

**Comment by purcell** [comment]
Okay, so there's some useful feedback in the failing CI: essentially you're relying on newer features than are available in the oldest Emacs versions previously supported by haml-mode. Bumping the emacs dependency to 26.1 and adding a dependency on the `seq` package would probably do the trick, but another option would be that we just refresh my `flymake-haml` code and put the dependencies there. That way the dependencies are granular (and not unnecessarily restrictive here), and an old unusable package starts working again, and nicely. What do you think?

**Comment by purcell** [comment]
Thinking about this, I'd be inclined to say that since `haml-lint` is an opinionated add-on tool, we'd still want `flymake-haml` to support basic syntax checking with just the "haml" command. In that case, we could provide new-style flymake backends for both tools in the `flymake-haml` package and update the docs accordingly. Alternatively, we could make a separate little `flymake-haml-lint` package. Happy to join forces to do that.

**Comment by gcentauri** [comment]
@purcell - hi! thanks for taking a look!

you've got some great points and i'm inclined to agree.
even though these old versions are pretty old, `haml-mode` works just fine as is without newer dependencies.

updating `flymake-haml` and adding an additional (optional) backend for `haml-lint` sounds very reasonable to me.

i will work on getting that started, but i may be a bit slow on that. in the meantime i'll leave this PR open until we can move discussion over to `flymake-haml` :)

one other point i will add, I have FSF copyright assignment sorted out, so if there's enough momentum to commit some flymake backends to Emacs itself, that is yet another alternative. personally, i'd prefer not making an additional package for `flymake-haml-lint`. we have a rubocop backend in `ruby-mode` so i was following that example originally.

**Comment by purcell** [comment]
Yeah, I noticed that `ruby-mode` also supports a basic syntax check too, so I think we should have two backends in `flymake-haml`, one for `haml` and the other for `haml-lint`.

**Comment by gcentauri** [comment]
moving the work to `flymake-haml`

https://github.com/purcell/flymake-haml/pull/1

**Pull request closed without merging**
